# Generated by Django 4.2.4 on 2024-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_product_image1_product_image2_product_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_listed',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
