# Generated by Django 4.2.4 on 2024-05-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_brand_description_alter_brand_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
