# Generated by Django 4.2.4 on 2024-06-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
