# Generated by Django 4.2.4 on 2024-06-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_login_name_alter_login_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
