# Generated by Django 4.2.4 on 2024-06-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
