# Generated by Django 4.2.4 on 2024-06-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_category_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
