# Generated by Django 4.2.4 on 2024-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
