# Generated by Django 4.2.4 on 2024-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0002_alter_account_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.IntegerField(blank=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
