# Generated by Django 4.2.4 on 2024-05-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0007_rename_name_login_username_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frntnd.register'),
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
