# Generated by Django 4.2.4 on 2024-05-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0009_alter_register_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
    ]
