# Generated by Django 4.2.4 on 2024-05-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0010_remove_register_email_remove_register_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Regi',
        ),
    ]
