# Generated by Django 4.2.4 on 2024-05-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0012_register_alter_otp_username_delete_regi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='state',
        ),
    ]
