# Generated by Django 4.2.4 on 2024-05-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0014_rename_account_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useraccount',
        ),
    ]
