# Generated by Django 4.2.4 on 2024-06-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0016_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='verified',
        ),
    ]
