# Generated by Django 4.2.4 on 2024-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0017_remove_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
