# Generated by Django 4.2.4 on 2024-06-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0018_otp_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='created_at',
            new_name='otpcreate_time',
        ),
    ]
