# Generated by Django 4.2.4 on 2024-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0019_rename_created_at_otp_otpcreate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
