# Generated by Django 4.2.4 on 2024-06-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0020_alter_otp_email_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
