# Generated by Django 4.2.4 on 2024-06-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0022_rename_otp_register_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
