# Generated by Django 4.2.4 on 2024-06-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0023_alter_register_email_alter_register_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='city',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.BigIntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='state',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
