# Generated by Django 4.2.4 on 2024-06-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0024_register_phone_alter_useraccount_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
