# Generated by Django 4.2.4 on 2024-06-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0025_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=True, max_length=100)),
                ('email', models.EmailField(default=True, max_length=254)),
                ('password', models.CharField(default=True, max_length=100)),
                ('phone', models.IntegerField(default=True)),
                ('otpcode', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
