# Generated by Django 4.2.4 on 2024-06-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0026_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
