# Generated by Django 4.2.4 on 2024-06-15 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_delete_login'),
        ('frntnd', '0027_alter_register_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='prodt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frntnd.useraccount'),
        ),
    ]
