# Generated by Django 4.2.4 on 2024-06-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0028_remove_cart_image_remove_cart_product_cart_prodt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='state',
        ),
    ]
