# Generated by Django 4.2.4 on 2024-06-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0029_remove_useraccount_address_remove_useraccount_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Useraccount',
        ),
    ]
