# Generated by Django 4.2.4 on 2024-06-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0034_alter_cart_price_alter_cart_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
