# Generated by Django 4.2.4 on 2024-06-19 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_brand_offer'),
        ('frntnd', '0035_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField(blank=True, default=1)),
                ('total', models.IntegerField(blank=True, default=1, null=True)),
                ('prodt', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frntnd.useraccount')),
            ],
        ),
    ]
