# Generated by Django 4.2.4 on 2024-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0039_alter_cart_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'ORDER_PROCESSED'), (3, 'ORDER_DELIVERED'), (4, 'ORDER_REJECTED')], default=0),
        ),
    ]
