# Generated by Django 4.2.4 on 2024-07-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0041_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_status',
        ),
    ]
