# Generated by Django 4.2.4 on 2024-07-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_product_offer'),
        ('frntnd', '0042_remove_cart_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prodt',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='frntnd.useraccount'),
        ),
    ]
