# Generated by Django 4.2.4 on 2024-07-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frntnd', '0043_alter_cart_prodt_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
